stages:
  - build

docker_build:
  stage: build
  image: docker:18-git
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:18-dind

  script:
    - docker info
