stages:
  - build

docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:latest
  variables:
    DOCKER_DRIVER: overlay2 # not sure if this is needed
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker info
