stages:
  - build

docker_build:
  stage: build
  image: circleci/python:2.7.14
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2 # not sure if this is needed
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker info